/******************************
File: create_tables.sql
Last Update: 1/16/2025
Description: This script defines the tables and constraints
             for the PICKEM_DB database.
******************************/


CREATE TABLE SCORING (
    PICK_WEIGHT     CHAR(1)         NOT NULL,
    REWARD          TINYINT         NOT NULL,
    PENALTY         TINYINT         NOT NULL

    CONSTRAINT PK_SCORING PRIMARY KEY (PICK_WEIGHT)
);

CREATE TABLE USERS (
    USER_ID         INT             NOT NULL    AUTO_INCREMENT,
    USERNAME        VARCHAR(25)     NOT NULL,
    PWDHASH         VARCHAR(25)     NOT NULL,
    NOTIFICATION_PREF   CHAR(1)     NULL,
    EMAIL_ADDRESS   VARCHAR(75)     NULL,
    PHONE           VARCHAR(10)     NULL,
    
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

CREATE TABLE PICKS (
    PICK_ID         VARCHAR(50)     NOT NULL,
    USER_ID         INT             NOT NULL,
    GAME_ID         VARCHAR(25)     NOT NULL,
    TEAM_PICKED     VARCHAR(25)     NULL,
    PICK_WEIGHT     CHAR(1)         NULL,

    CONSTRAINT PK_PICKS PRIMARY KEY (PICK_ID),
    CONSTRAINT FK_USERPICK 
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
    CONSTRAINT FK_PICKSCORE 
        FOREIGN KEY (PICK_WEIGHT) REFERENCES SCORING(PICK_WEIGHT)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE GAME_BOX_SCORES (
    GAME_ID         VARCHAR(25)     NOT NULL,
    TEAM_ID         VARCHAR(25)     NOT NULL,
    Q1_SCORE        SMALLINT        NULL,
    Q2_SCORE        SMALLINT        NULL,
    Q3_SCORE        SMALLINT        NULL,
    Q4_SCORE        SMALLINT        NULL,
    OVERTIME        SMALLINT        NULL,
    TOTAL           SMALLINT        NULL,
    GAME_FINISHED   TINYINT(1)      NOT NULL

    CONSTRAINT PK_GAME_BOX_SCORES PRIMARY KEY (GAME_ID, TEAM_ID)
);

CREATE TABLE LOCATIONS (
    STADIUM         VARCHAR(50)     NOT NULL,
    CITY            VARCHAR(50)     NOT NULL,
    STATE           VARCHAR(20)     NULL,
    LATITUDE        DECIMAL(19,16)  NULL,
    LONGITUDE       DECIMAL(19,16)  NULL,

    CONSTRAINT PK_LOCATIONS PRIMARY KEY (STADIUM, CITY)
);

CREATE TABLE TEAM_RECORD (
    TEAM_ID         VARCHAR(25)     NOT NULL,
    RECORD_TYPE     VARCHAR(10)     NOT NULL,
    WINS            TINYINT         NULL,
    LOSSES          TINYINT         NULL,
    TIES            TINYINT         NULL,

    CONSTRAINT PK_TEAM_RECORD PRIMARY KEY (TEAM_ID, RECORD_TYPE)
);


/*** GAMES ***
-- PRIMARY KEY: 
CREATE TABLE GAMES (
    GAME_ID         VARCHAR(25)     NOT NULL    PRIMARY KEY,
    LEAGUE          VARCHAR(5)      NOT NULL,
    WEEK            TINYINT         NOT NULL,
    CBS_CODE        VARCHAR(50)     NOT NULL,
    ESPN_CODE       VARCHAR(50)     NOT NULL,
    FOX_CODE        VARCHAR(50)     NOT NULL,
    VEGAS_CODE      VARCHAR(50)     NOT NULL,
    AWAY_TEAM_ID    VARCHAR(25)     NOT NULL,
    HOME_TEAM_ID    VARCHAR(25)     NOT NULL,
    DATE            DATE            NULL,
    TIME            TIME            NULL,
    TV_COVERAGE     VARCHAR(25)     NULL,
    STADIUM         VARCHAR(50)     NULL,
    CITY            VARCHAR(50)     NULL,
    STATE           VARCHAR(50)     NULL

    -- FOREIGN KEY (AWAY_TEAM_ID) REFERENCES TEAMS(TEAM_ID)
    -- FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAMS(TEAM_ID)
); */