/******************************
File: proc_drop_constraints.sql
Last Update: 3/5/2025
Description: This script drops all constraints from the PICKEM_DB
******************************/

-- USE PICKEM_DB;

DELIMITER //

DROP PROCEDURE IF EXISTS PROC_DROP_CONSTRAINTS //

CREATE PROCEDURE PROC_DROP_CONSTRAINTS ()
BEGIN

    ALTER TABLE PICKS 
		DROP CONSTRAINT FK_GAME_PICK;
	ALTER TABLE PICKS 
		DROP CONSTRAINT FK_USERPICK;
	ALTER TABLE GAMES 
		DROP CONSTRAINT FK_HOME_BOX_SCORES;
	ALTER TABLE GAMES
		DROP CONSTRAINT FK_AWAY_BOX_SCORES;
	ALTER TABLE GAMES 
		DROP CONSTRAINT FK_GAME_LOCATIONS;

END //

DELIMITER ;