/******************************
File: proc_load_team.sql
Last Update: 2/25/2025
Description: This script inserts a new team record if one does not
				already exist or updates the existing one
******************************/

USE PICKEM_DB;

DELIMITER //


DROP PROCEDURE IF EXISTS PROC_LOAD_TEAM //

CREATE PROCEDURE PROC_LOAD_TEAM (
	IN IN_TEAM_ID VARCHAR(100),
    IN IN_LEAGUE VARCHAR(5),
	IN IN_CBS_CODE VARCHAR(50),
	IN IN_ESPN_CODE VARCHAR(50),
	IN IN_FOX_CODE VARCHAR(50),
	IN IN_VEGAS_CODE VARCHAR(50),
	IN IN_CONFERENCE_CODE VARCHAR(25),
	IN IN_CONFERENCE_NAME VARCHAR(50),
	IN IN_DIVISION_NAME VARCHAR(50),
	IN IN_TEAM_NAME VARCHAR(50),
	IN IN_TEAM_MASCOT VARCHAR(50),
	IN IN_POWER_CONFERENCE BOOLEAN,
	IN IN_TEAM_LOGO_URL VARCHAR(100),
	IN IN_PRIMARY_COLOR VARCHAR(10),
	IN IN_ALTERNATE_COLOR VARCHAR(10)
)
BEGIN
	
    IF (SELECT COUNT(*) FROM TEAMS WHERE TEAM_ID = IN_TEAM_ID) = 0 THEN
		
        # Insert new row 
        INSERT INTO TEAMS (TEAM_ID, LEAGUE, CBS_CODE, ESPN_CODE, FOX_CODE, VEGAS_CODE,
							CONFERENCE_CODE, CONFERENCE_NAME, DIVISION_NAME,
							TEAM_NAME, TEAM_MASCOT, POWER_CONFERENCE, TEAM_LOGO_URL,
                            PRIMARY_COLOR, ALTERNATE_COLOR)
			VALUES (IN_TEAM_ID, IN_LEAGUE, IN_CBS_CODE, IN_ESPN_CODE, IN_FOX_CODE, 
					IN_VEGAS_CODE, IN_CONFERENCE_CODE, IN_CONFERENCE_NAME, 
                    IN_DIVISION_NAME, IN_TEAM_NAME, IN_TEAM_MASCOT, IN_POWER_CONFERENCE, 
                    IN_TEAM_LOGO_URL, IN_PRIMARY_COLOR, IN_ALTERNATE_COLOR);
		
        COMMIT;
	
    ELSE
        
        # Update existing row
        UPDATE TEAMS 
			SET 
				#CBS_CODE = IN_CBS_CODE,
				#ESPN_CODE = IN_ESPN_CODE, 
				#FOX_CODE = IN_FOX_CODE, 
				#VEGAS_CODE = IN_VEGAS_CODE,
                TEAM_NAME = IN_TEAM_NAME,
                TEAM_MASCOT = IN_TEAM_MASCOT,
				CONFERENCE_CODE = IN_CONFERENCE_CODE, 
				CONFERENCE_NAME = IN_CONFERENCE_NAME, 
				DIVISION_NAME = IN_DIVISION_NAME,
				POWER_CONFERENCE = IN_POWER_CONFERENCE, 
				TEAM_LOGO_URL = IN_TEAM_LOGO_URL,
                PRIMARY_COLOR = IN_PRIMARY_COLOR,
                ALTERNATE_COLOR = IN_ALTERNATE_COLOR
			WHERE TEAM_ID = IN_TEAM_ID;
<<<<<<< HEAD
            
		COMMIT;
=======
>>>>>>> 612ec98 (Update ESPN_CODE, CBS_CODE, FOX_CODE and VEGAS_CODE if TEAM_ID exists in TEAM)
        
	END IF;

END //

DELIMITER ;
