/******************************
File: proc_load_game.sql
Last Update: 3/23/2025
Description: This script inserts a new game record if one does not
				already exist or updates the existing one
******************************/

USE PICKEM_DB;

DELIMITER //

DROP PROCEDURE IF EXISTS PROC_LOAD_GAME //

CREATE PROCEDURE PROC_LOAD_GAME (
	IN IN_GAME_ID VARCHAR(100),
    IN IN_LEAGUE VARCHAR(5),
    IN IN_WEEK TINYINT,
    IN IN_YEAR YEAR,
    IN IN_CBS_CODE VARCHAR(50),
    IN IN_ESPN_CODE VARCHAR(50),
    IN IN_FOX_CODE VARCHAR(50),
    IN IN_VEGAS_CODE VARCHAR(50),
    IN IN_AWAY_TEAM_ID VARCHAR(50),
    IN IN_HOME_TEAM_ID VARCHAR(50),
    IN IN_DATE DATE,
    IN IN_TIME TIME,
    IN IN_TV_COVERAGE VARCHAR(25),
    IN IN_STADIUM VARCHAR(50),
    IN IN_CITY VARCHAR(50),
    IN IN_GAME_FINISHED BOOLEAN
)
BEGIN
	
    IF (SELECT COUNT(*) FROM GAMES WHERE GAME_ID = IN_GAME_ID) = 0 THEN
        
        /*** Insert New Game Row ***/
        INSERT INTO GAMES (GAME_ID, LEAGUE, WEEK, YEAR, CBS_CODE, ESPN_CODE, FOX_CODE, 
							VEGAS_CODE, AWAY_TEAM_ID, HOME_TEAM_ID, DATE, TIME, 
                            TV_COVERAGE, STADIUM, CITY, GAME_FINISHED)
			VALUES (IN_GAME_ID, IN_LEAGUE, IN_WEEK, IN_YEAR, IN_CBS_CODE, IN_ESPN_CODE, 
					IN_FOX_CODE, IN_VEGAS_CODE, IN_AWAY_TEAM_ID, IN_HOME_TEAM_ID, IN_DATE, 
                    IN_TIME, IN_TV_COVERAGE, IN_STADIUM, IN_CITY, IN_GAME_FINISHED);
    
    ELSE
        
        /*** Update existing row ***/
		UPDATE GAMES 
		SET 
			LEAGUE = IN_LEAGUE, 
			WEEK = IN_WEEK,
            YEAR = IN_YEAR,
			CBS_CODE = IN_CBS_CODE, 
			ESPN_CODE = IN_ESPN_CODE, 
			FOX_CODE = IN_FOX_CODE, 
			VEGAS_CODE = IN_VEGAS_CODE, 
			AWAY_TEAM_ID = IN_AWAY_TEAM_ID,
			HOME_TEAM_ID = IN_HOME_TEAM_ID, 
			DATE = IN_DATE, 
			TIME = IN_DATE, 
			TV_COVERAGE = IN_TV_COVERAGE, 
			STADIUM = IN_STADIUM,
            CITY = IN_CITY,
			GAME_FINISHED = IN_GAME_FINISHED
		WHERE GAME_ID = IN_GAME_ID;
        
	END IF;

END //

DELIMITER ;
