/******************************
File: proc_load_odds.sql
Last Update: 2/25/2025
Description: This script inserts a new odds record if one does not
				already exist or updates the existing one
******************************/

USE PICKEM_DB;

DELIMITER //

DROP PROCEDURE IF EXISTS PROC_LOAD_ODDS //

CREATE PROCEDURE PROC_LOAD_ODDS (
	IN IN_GAME_ID         VARCHAR(100),
	IN IN_GAME_CODE       VARCHAR(100),
	IN IN_SOURCE          VARCHAR(10),
	IN IN_AWAY_MONEYLINE  VARCHAR(10),
	IN IN_HOME_MONEYLINE  VARCHAR(10),
	IN IN_AWAY_SPREAD     VARCHAR(5),
	IN IN_HOME_SPREAD     VARCHAR(5),
	IN IN_OVER_UNDER      VARCHAR(5),
	IN IN_AWAY_WIN_PERCENTAGE VARCHAR(5),
	IN IN_HOME_WIN_PERCENTAGE VARCHAR(5)
)
BEGIN
	
    IF (SELECT COUNT(*) FROM ODDS WHERE GAME_CODE = IN_GAME_CODE AND SOURCE = IN_SOURCE) = 0 THEN
		
        # Insert new row 
        INSERT INTO ODDS (GAME_ID, GAME_CODE, SOURCE, AWAY_MONEYLINE,
					HOME_MONEYLINE, AWAY_SPREAD, HOME_SPREAD, 
                    OVER_UNDER, AWAY_WIN_PERCENTAGE, HOME_WIN_PERCENTAGE)
			VALUES (IN_GAME_ID, IN_GAME_CODE, IN_SOURCE, IN_AWAY_MONEYLINE,
					IN_HOME_MONEYLINE, IN_AWAY_SPREAD, IN_HOME_SPREAD, 
                    IN_OVER_UNDER, IN_AWAY_WIN_PERCENTAGE, IN_HOME_WIN_PERCENTAGE);
	
    ELSE
        
        # Update existing row
        UPDATE ODDS 
			SET 
				AWAY_MONEYLINE = IN_AWAY_MONEYLINE,
				HOME_MONEYLINE = IN_HOME_MONEYLINE, 
                AWAY_SPREAD = IN_AWAY_SPREAD, 
                HOME_SPREAD = IN_HOME_SPREAD, 
				OVER_UNDER = IN_OVER_UNDER, 
                AWAY_WIN_PERCENTAGE = IN_AWAY_WIN_PERCENTAGE, 
                HOME_WIN_PERCENTAGE = IN_HOME_WIN_PERCENTAGE
			WHERE GAME_CODE = IN_GAME_CODE
				AND SOURCE = IN_SOURCE;
        
	END IF;
    
    COMMIT;

END //

DELIMITER ;
